networks:
  my-isolated-network:
    name:events-network

services:
  event-emitter-1:
    image: ghcr.io/estebanlopezgomez/dockerfile_labo:v1.0
    command:
      - event-emitter
      - --port=9877
      - --multicast=239.0.0.1
      - --auto
      
  event-client:
    build: ghcr.io/estebanlopezgomez/dockerfile_labo:v1.0
    command:
      - get-event
      - --port=9876

  event-server:
    build: ghcr.io/estebanlopezgomez/dockerfile_labo:v1.0
    command:
      - event-server
      - --port=9876
      - --multicast=239.0.0.1:9877
      - --threads=10
